### ISSUE TITLE
Replace Procfile with Flynnfile

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1084]
We currently use a `Procfile` to declare process types, but this only supports declaring how to start the job, whereas process types are [more complex than that](https://github.com/flynn/flynn/blob/master/controller/types/types.go#L42-L51).

We should replace this with a `Flynnfile` which can be parsed by the receiver and supports declaring all aspects of a process type (e.g. mounted volumes, ports, services, healthchecks etc.).

The `Flynnfile` could also declare pre / post deploy hooks once supported.

**Comment by lmars** [comment]
We should ensure that we keep backwards compatibility.

**Comment by thomasfedb** [comment]
I would be careful about removing the `Procfile` altogether, unless you can get foreman to support your format.

**Comment by lmars** [comment]
@thomasfedb 

> I would be careful about removing the Procfile altogether, unless you can get foreman to support your format.

Flynn doesn't use Foreman, it parses the `Procfile` directly and extracts the process types (see [here](https://github.com/flynn/flynn/blob/master/slugbuilder/builder/build.sh#L149-L155)), so by "Replace Procfile" I mean "Replace the file which Flynn uses to define processes". Users can still have a `Procfile` in their project for use locally (which will be a fallback), but by default Flynn will look for a `Flynnfile`.

I don't think trying to redefine the `Procfile` format to support Flynn is going to be useful to a lot of people that use Procfiles (I'm pretty sure the current format is simply `TYPE: COMMAND`).

**Comment by thomasfedb** [comment]
Right, so it was more hijacking to beging with anyway.

**Comment by lmars** [comment]
The `Flynnfile` could have a `packages` section which uses [heroku-buildpack-apt](https://github.com/ddollar/heroku-buildpack-apt) to install packages using `apt-get`.

**Comment by geovanisouza92** [comment]
@lmars I'd recent problems with heroku-buildpack-apt on flynn buildpack caching, and I think that one session exclusively for this can be nice, although I feel that this special case is not so special.

Anyway, creating another file format can be nice to fit with flynn ecosystem, but could detour flynn of nice existing tools like Foreman/Honcho or even Docker Compose, that I particularly think that is not so awesome substitute for Fig ('cause is just a rebrand and rewrite of the tool), without any additions.

So I think it may be nice to have a new file format to configure everything in one place, but I worry that this new format can accumulate so many others like Procfile, [fig | docker-compose].yml, terraform.yml , etc, etc, etc.

**Comment by lmars** [comment]
From @thomasfedb in #1503:

> The Flynnfile should allow a developer to specify a list of environment variables that are required at each of buildtime and runtime.

> Flynn should prompt the user to specify these variables before attempting to build and/or run the application.

**Comment by arekkas** [comment]
Here are some example for application manifests:

- http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#optional-attributes
- https://blog.heroku.com/archives/2014/5/22/introducing_the_app_json_application_manifest

Also, I'm working on a manifest for [gitdeploy.io](https://gitdeploy.io):

- https://github.com/ory-am/gitdeploy/blob/master/GITDEPLOY-PROPOSAL.md

**Comment by lmars** [comment]
We should consider adding this soon to help users who want to do more than just have a routable `web` service (e.g. see [this user in IRC](https://botbot.me/freenode/flynn/2015-12-07/?msg=55610473&page=2) who wants to run an SMTP service).

Some example formats:

### TOML

```toml
[processes.web]
command     = "start web"
service     = "my-app-web"
port        = 8080
healthcheck = { type = "http", path = "/ping", match = "pong" }

[resources]
postgres = true
redis    = true
```

### YAML

```yaml
processes:
  web:
    command: "start web"
    service: my-app-web
    port:    8080
    healthcheck:
      type:  "http"
      path:  "/ping"
      match: "pong"
resources:
  postgres: true
  redis:    true
```

### JSON

```json
{
  "processes": {
    "web": {
      "command": "start web",
      "service": "my-app-web",
      "port":    8080,
      "healthcheck": {
        "type":  "http",
        "path":  "/ping",
        "match": "pong"
      }
    }
  },
  "resources": {
    "postgres": true,
    "redis":    true,
  }
}
```

### Lua

```lua
processes = {
  web = {
    command = "start web"
    service = "my-app-web"
    port    = 8080
    healthcheck = {
      type = "http"
      path = "ping"
      match = "pong"
    }
  }
}

resources = {
  postgres = true
  redis    = true
}
```

I included Lua as it is a scripting language and could give more flexibility, for example exposing functions to declare complex dependencies more concisely.

Just some thoughts to get the discussion going.

**Comment by josephglanville** [comment]
I think TOML would be great. Lua might err on the side of a bit too powerful.
If it can be easily executed in a sandbox though maybe not a bad idea, just concerned about security in multi-tenant environments (when we get there).

**Comment by temujin9** [comment]
-1 for JSON: definitely not user friendly. I abstract away from it every chance I get.

TOML or YAML could both work.

I'm actually quite fond of scriptable interfaces, especially at this level. I also see the security concerns, however. Not as sure about Lua specifically, mostly due to unfamiliarity. I have no perfect suggestions for replacement, and could cope with learning / pushing Lua at developers.

**Comment by thomasfedb** [comment]
I'd go for more expressive power if possible, mostly because I want to be able to use my `Flynnfile` to hook up a few things, to avoid magical numbers/strings.

In particular, I'd like a way to choose my own ENV variables for PG info, something like:

```yaml
processes:
  web:
    cmd: "unicorn_rails ..."
    env:
      THREADS: 4
      DB_HOST: resources.pg1.hostname
      DB_USER: resources.pg1.username
      DB_PASS: resources.pg1.password

...

resources:
  pg1:
    type: "postgres"
```
