### ISSUE TITLE
host: Runs out of space after x deployments

### ISSUE THREAD

**Issue by arekkas** [flynn/flynn#1565]
Hosts run out of space after a certain amount of deployments (my guess is somewhere around 100-400), although only a few apps (2-3) are running - all others have been deleted:

```
$ git push flynn master
....
remote: Build failed: exec: job exited with status 1        
remote: mkdir: cannot create directory '/tmp/cache/pip': No space left on device  
```

This issue has already been mentioned in #1523 . It does not look like #1528 solved this issue. @lmars mentioned in IRC that this might be caused by using a sparse file, instead of using a dedicated drive

**Please note that the VM's disk size is only 50GB, not > 70GB as suggested by `/var`**

**Comment by arekkas** [comment]
```
# for i in G M K; do du -ah | grep [0-9]$i | sort -nr -T /nope -S 10000000 -k 1; done | head -n 30
du: cannot access ‘./proc/25076’: No such file or directory
du: cannot access ‘./proc/25125/task/25125/fd/4’: No such file or directory
du: cannot access ‘./proc/25125/task/25125/fdinfo/4’: No such file or directory
du: cannot access ‘./proc/25125/fd/4’: No such file or directory
du: cannot access ‘./proc/25125/fdinfo/4’: No such file or directory
78G	.
77G	./var
76G	./var/lib
48G	./var/lib/flynn/volumes/zfs
48G	./var/lib/flynn/volumes
48G	./var/lib/flynn
35G	./var/lib/flynn/volumes/zfs/vdev/flynn-default-zpool.vdev
35G	./var/lib/flynn/volumes/zfs/vdev
29G	./var/lib/docker/aufs
29G	./var/lib/docker
16G	./var/lib/docker/aufs/mnt
14G	./var/lib/flynn/volumes/zfs/mnt
14G	./var/lib/docker/aufs/mnt/tmp-acf6b4eecfb348219330c39986493233
13G	./var/lib/flynn/volumes/zfs/mnt/e7b868542018481db0782126697edfb6
13G	./var/lib/docker/aufs/mnt/tmp-acf6b4eecfb348219330c39986493233/data
13G	./var/lib/docker/aufs/diff
8.0K	./var/lib/docker/aufs/mnt/tmp-7b7c07c044464e70a62be477f758dff6/usr/share/alsa/cards/Echo_Echo3G.conf
8.0K	./var/lib/docker/aufs/diff/f97a35e8b7f32c5db5eb58e1aa4d4042fd4b36a5dfa916996925408f76c925ba/usr/share/alsa/cards/Echo_Echo3G.conf
6.6G	./var/lib/flynn/volumes/zfs/mnt/e7b868542018481db0782126697edfb6/pg_xlog
6.6G	./var/lib/docker/aufs/mnt/tmp-acf6b4eecfb348219330c39986493233/data/pg_xlog
6.5G	./var/lib/flynn/volumes/zfs/mnt/e7b868542018481db0782126697edfb6/base
6.5G	./var/lib/docker/aufs/mnt/tmp-acf6b4eecfb348219330c39986493233/data/base
6.4G	./var/lib/flynn/volumes/zfs/mnt/e7b868542018481db0782126697edfb6/base/16792
6.4G	./var/lib/docker/aufs/mnt/tmp-acf6b4eecfb348219330c39986493233/data/base/16792
1.1G	./var/lib/flynn/volumes/zfs/mnt/e7b868542018481db0782126697edfb6/base/16792/12130.5
1.1G	./var/lib/flynn/volumes/zfs/mnt/e7b868542018481db0782126697edfb6/base/16792/12130.4
1.1G	./var/lib/flynn/volumes/zfs/mnt/e7b868542018481db0782126697edfb6/base/16792/12130.3
1.1G	./var/lib/flynn/volumes/zfs/mnt/e7b868542018481db0782126697edfb6/base/16792/12130.2
1.1G	./var/lib/flynn/volumes/zfs/mnt/e7b868542018481db0782126697edfb6/base/16792/12130.1
1.1G	./var/lib/flynn/volumes/zfs/mnt/e7b868542018481db0782126697edfb6/base/16792/12130
```

It seems like both flynn/volumes as well as docker/aufs take a lot of space.

**Comment by arekkas** [comment]
Postgres is taking 13GB of space:

```
# df -h
Filesystem                                      Size  Used Avail Use% Mounted on
/dev/xvda1                                       50G   50G     0 100% /
none                                            4.0K     0  4.0K   0% /sys/fs/cgroup
udev                                            1.9G   12K  1.9G   1% /dev
tmpfs                                           377M  500K  376M   1% /run
none                                            5.0M     0  5.0M   0% /run/lock
none                                            1.9G  2.3M  1.9G   1% /run/shm
none                                            100M     0  100M   0% /run/user
/dev/xvdb                                       3.9G  8.1M  3.7G   1% /mnt
flynn-default/90c5fb4de5ad44799a4e6b2157db04e9   21G   19M   21G   1% /var/lib/flynn/volumes/zfs/mnt/90c5fb4de5ad44799a4e6b2157db04e9
flynn-default/e7b868542018481db0782126697edfb6   34G   13G   21G  39% /var/lib/flynn/volumes/zfs/mnt/e7b868542018481db0782126697edfb6
flynn-default/97317730f3044497b23ceb0831939b56   21G     0   21G   0% /var/lib/flynn/volumes/zfs/mnt/97317730f3044497b23ceb0831939b56
root@ip-10-0-2-249:/var/lib/flynn/volumes/zfs/mnt/e7b868542018481db0782126697edfb6# ls
base    pg_clog      pg_hba.conf    pg_logical    pg_notify    pg_serial     pg_stat      pg_subtrans  pg_twophase  pg_xlog               postgresql.conf  postmaster.pid
global  pg_dynshmem  pg_ident.conf  pg_multixact  pg_replslot  pg_snapshots  pg_stat_tmp  pg_tblspc    PG_VERSION   postgresql.auto.conf  postmaster.opts
```

**Comment by arekkas** [comment]
I've also tried doing:

```
# docker images --no-trunc| grep none | awk '{print $3}' | xargs -r docker rmi
Deleted: 7a01d9167e2521daf95e25ec1d99107cd56d4c967405220bf859ba782b3e3725
Deleted: cf910813dd33c38cc3cd66200d62ff74ac43fe81e18745e3a4249369b1b1f478
Deleted: 6eb623cb8d41a95e069d1d8dc4c027825582627cbda991bb09d75ffa2c0b70da
Deleted: f6ff71f6a5b77ca9d0ec4b58ef012c293ae72686240ec920846449c2e3637bee
Deleted: ccbf7fe5698c5a71c0870b72a504f15719e1353f3315437f7dd101011ecff27a
Deleted: 22ad01d1384112fb09992e4ceea1bb0cf493a3f601e9a8e4ae5610b5c0d691ea
Deleted: 1f74bdac412ab7490eb5ce785a39708e5fbe7eaadfb1959b618cf338a28740d3
Deleted: 7a652d0ceb42c30316f140d19f13c42cac9bd0f9b90ba5b64d49fe6d4eb7c645
Deleted: e398834e928f8b686fe8fe099c2398b353a4461b27e4b3c1dd9f8b93004e34e2
Deleted: ad16466492c6b5b1777c7ddb8694821a83e77259f03eb140e7662bad54e2eaba
Deleted: d27f4ec68842992d5e2e76a91297c360ef4c09c27d207007d932f7c9ac2f23a3
Deleted: 7ea2d3b45b0c212b0559467ac3f87ef4eaa5d7ac6b45013c551bcf1e9bf42fec
Deleted: 675e29ec8d8c822bad29f5d181f7738a786404aae266e3081d394e60f5121e6c
Deleted: 155515d25c6e5c7b88eb21f9da4b79fd42383cd01d345f03225c22fa57288997
Deleted: a7445aa540ba3b73e5fe728fcb23c89a1340d5c6514005aa70d351566082f371
Deleted: aafd81300c20e3874c86902c8239f8aea64af5fe23056a7c549c61dc5ad0cd55
Deleted: 35ae86d09cf4dbb683843dbcd4d293b8f0a9f5dbe9fd5e54c4c9822329ca85b6
Deleted: 2d02c14a7b78910a1005b8edac261607c994a8341fe7a363474c30b688bd08d4
Deleted: 472e639c33a51f6c5f730633fea2e40a24ed049c13e90542165650aed11a713b
Deleted: 3f5620a3fe71ca015f4af8928fb5d16d401d179d1a374e96d17e7eb838576d53
Deleted: 564abad33e8584ccf58f5d33fdf65a1b1c5efef1d5538df7b6f7aff472a8b0b4
Deleted: 600fa5e285adc6e71fac46fd04d8fa9fc009d73f5afe4624383557ee4f65c885
Deleted: 27c989e7a4a0431b1d6a25cd582ab6346f7a8a35fc388fbc2ebe72288fb4ff1d
Deleted: 67d6d0a0e5d891d246c1b101f13d49a202ef99afb7a62b7253501d6484af0e78
Deleted: 2983b4213660c79d847558fc96b5306c51ed5af616ed76b9b86ae6227e63c359
Deleted: d85779a14fab93fed1f6578cdb9ced0bfc70636fd8e89faad23597d8eba9eca2
Deleted: 9bdf7ad2bae032a4d2bef408bea87e764bb84f5b3571cfdec6c68014f0b2934b
Deleted: 2f50ed460f702c7280364737519ac9ba676d3cadbfe089ae611c6f0965c35a84
Deleted: 2c7cdd7d0013bd991198beb402b716d375683f57d985821be5cf495e4ee5fd8b
Deleted: 97e28a4491458106365919082f350b636a038eb4fe7f9dcda5bc810321a9f051
Deleted: 9d90ec3e9042dc0604822e6a5394bbd316ec564206bec5c8fcfe28379fcf032a
Deleted: 10bfd220cf5966b788612ea7a5d6238e56cdc8935ffba3447849dbeb34636725
Deleted: 37cc314b9684f118eee13b68df60283392f247d2492c74cdd17f0f180a678995
Deleted: 5ebbfc70e07910a092f18f505c43ab9f6c03e1d8c177cc866e3fb87a41b0b49c
Deleted: b548fa1ffea99c82fc585ada1789dbae82f0a00e4cef181ca1b433433be3c7e8
Deleted: d01fd3c90c9c166f02eeaec7b4b9809a220c64c92b7dfbcb8b1ead42c2b9003a
Deleted: c42eb2a80ca80e110097b44c111a0c1deac85f9603b36e3d8dc6d27324297b15
Deleted: 78f7a19d436e12fd435d0446dd22e9582f8164833eb22e3642a14998eef531af
Deleted: d041fd42d5170ed8fa76ba38263b08eebfa3eb8a92c62a2a24baf40b7b0e822d
Deleted: 0c3124242df8a570eb39c232f6a8586812e97b5357c992e64725cd14f469ce15
Deleted: f3821a00ca2f81a171749a4127f91c5d310835b3642babefb480256c9c5d9b08
Deleted: 0bf327eb1f91fe6ef1c38a2aab0acb43fc25f365ee813bd655402a261d7cd759
Deleted: fc1ae8f2a183cb341447b433a254d13223df0faae34e1e3e4221ec0a859b1494
Deleted: 40c8360c62253bb3939347e07632e1bcb3c38e8c4c98cae1b5ff52e1e95ae8ef
Deleted: f97a35e8b7f32c5db5eb58e1aa4d4042fd4b36a5dfa916996925408f76c925ba
Deleted: f90b0e99841dae154e9fb342ff259279048570983b09dea51665318479a7da68
Deleted: c40496787f7c3c3f84e1935d014113cb711a2577c062e5fd1a01245a41e290fa
Deleted: 95f11acdce339b9e03fb571139a31611039b21dd77e07c51db8822118dcf22e6
Deleted: 756004de5d1a52c3a470965c308947af829c4a311157adf22dbe71ea48cc39f0
Deleted: a41a9c0d6465ef3ffa84e52fa522b6ddad1841743829670fb55ddae06ea19ad7
Deleted: 45ea0e14264b4b2682ab38c1c10954f27a6ffaee164cd640c8f0fc311bd8ac21
Deleted: beb81b1c490f46f80b4cf2a6f92559e7dfd56d358223f23b01a4d1d75d105b4e
Deleted: 184af8860f22e7a87f1416bb12a32b20d0d2c142f719653d87809a6122b04663
Deleted: 0dc93e107f111bf2336516d171ac2b4ea1cd56b9cd2686d773b8208f1e265b3a
Deleted: a643fa1f27423cb7d426d52aed06d846fd6a4518b44da74ab03fc78cbfae6a04
Deleted: 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158
```

ass suggested [here](https://meta.discourse.org/t/low-on-disk-space-cleaning-up-old-docker-containers/15792) without any effect what so ever.

**Comment by arekkas** [comment]
```
root@ip-10-0-2-249:/var/lib/flynn/volumes/zfs/mnt# zdb
flynn-default:
    version: 5000
    name: 'flynn-default'
    state: 0
    txg: 4
    pool_guid: 16650219447766509816
    errata: 0
    hostid: 3121275571
    hostname: 'ip-10-0-2-249'
    vdev_children: 1
    vdev_tree:
        type: 'root'
        id: 0
        guid: 16650219447766509816
        create_txg: 4
        children[0]:
            type: 'file'
            id: 0
            guid: 16196100719820612248
            path: '/var/lib/flynn/volumes/zfs/vdev/flynn-default-zpool.vdev'
            metaslab_array: 34
            metaslab_shift: 28
            ashift: 9
            asize: 36886282240
            is_log: 0
            create_txg: 4
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data
root@ip-10-0-2-249:/var/lib/flynn/volumes/zfs/mnt# zpool status
  pool: flynn-default
 state: ONLINE
status: One or more devices are faulted in response to IO failures.
action: Make sure the affected devices are connected, then run 'zpool clear'.
   see: http://zfsonlinux.org/msg/ZFS-8000-HC
  scan: none requested
config:

	NAME                                                        STATE     READ WRITE CKSUM
	flynn-default                                               ONLINE       0    74     0
	  /var/lib/flynn/volumes/zfs/vdev/flynn-default-zpool.vdev  ONLINE       0   151     0

errors: 74 data errors, use '-v' for a list
root@ip-10-0-2-249:/var/lib/flynn/volumes/zfs/mnt# zfs list -t all
no datasets available
```

After doing `zpool clear flynn-default`, `zfs` started working for a few seconds:

`# zfs get all`: https://gist.github.com/arekkas/db07830d286225285233
