### ISSUE TITLE
Deploying from Travis

### ISSUE THREAD

**Issue by Snugug** [flynn/flynn#2694]
I'm attempting to deploy a site to Flynn from Travis, and I'm running in to a couple of showstoppers.

1) When attempting to install the CLI, there's a permission denied trying to write to `/user/local/bin`
2) Having renamed the filename to `.flynn`, trying to `cluser add` my cluster I'm getting an `unknown cluster` error

I've tried looking around, and I can't seem to find anyone deploying to Flynn from Travis or a working example. Here's my travis stuff:

```yaml
language: node_js
node_js:
  - 'v5'

#########################
## Deploy
#########################
before_deploy: 'L=.flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L'

deploy:
  skip_cleanup: true
  provider: script
  script: sh ./.deploy.sh
  on:
    branch: master
```

```bash
#!/bin/bash

#########################
## Adapted from https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
#########################
set -e # exit with nonzero exit code if anything fails

# Initialize Flynn
./.flynn cluster add -p ${FLYNN_CLUSTER} default ${FLYNN_URL} ${FLYNN_TOKEN}
./.flynn create ${FLYNN_NAME}

# Configure Git
git config user.name "Travis CI"
git config user.email "deploybot@travis.ci"

# Commit all the things into the repo
git init
git add .
git commit -m ":shipit: Deploy to Flynn"

# Force push to gh-pages
git push flynn master
```
