### ISSUE TITLE
`JDBC_DATABASE_URL` contains `sslmode=require` but ssl is not supported

### ISSUE THREAD

**Issue by bobvanderlinden** [flynn/flynn#3231]
When using Flynn with Postgres and a Java application `JDBC_DATABASE_URL` is passed to the application. In my case its value was:

```
JDBC_DATABASE_URL=jdbc:postgresql://leader.postgres.discoverd:5432/057931316179a89783c995a991a2753f?user=d6485be1962bb6cc692f94f30f0145c1&password=8e67f2597ef25004ba8d534ca5dad0d8&sslmode=require
```

The Java application tries to connect to the database, but this results in an exception:

```
org.postgresql.util.PSQLException: The server does not support SSL.
```

From what I gathered postgres SSL is not (yet?) supported by `leader.postgres.discoverd` (#2136). That means `sslmode=require` should not be passed to the application. Rather, `sslmode=disable` should be used. I've now hardcoded `sslmode=disable` into my application to workaround this problem.

I'm presuming this is coded in the Heroku Gradle buildpack(?) or Postgres addon(?), since Heroku does support ssl postgres connections.

What is the best way to handle/workaround this?

**Comment by titanous** [comment]
Yes, that variable appears to be added here: https://github.com/heroku/heroku-buildpack-jvm-common/blob/7bd3a67940e87447bde0b3836c6ed40bc852f612/opt/jdbc.sh

For now you can specify the `JDBC_DATABASE_URL` env var manually, the buildpack should not override it.

The current plan is to allow database credentials to be templated into env vars in the upcoming Flynnfile (#1084).

We will add TLS for external access to postgres, but internally it will stay plaintext as we're going to encrypt all traffic on the overlay network instead of trying to get every service to implement their own TLS termination in-process.

**Comment by bobvanderlinden** [comment]
> For now you can specify the JDBC_DATABASE_URL env var manually, the buildpack should not override it.

How can I specify `JDBC_DATABASE_URL`? It is assigned by Flynn and can change at anytime?

> The current plan is to allow database credentials to be templated into env vars in the upcoming Flynnfile

Nice. Having a Flynnfile to configure the application sounds like a good step.

Just to note, this is my first time using Flynn. First application deployed.

**Comment by titanous** [comment]
> It is assigned by Flynn and can change at anytime?

The values in it are currently static, generated when you run `flynn resource add`. We will implement Flynnfiles before any changes that would make it dynamic.

**Comment by IsNull** [comment]
We currently use it this way on flynn:

```yaml
spring:
    datasource:
        platform: postgres
        dataSourceClassName: "org.postgresql.Driver"
        url: jdbc:postgresql://${PGHOST}:5432/${PGDATABASE}?sslmode=disable
        username: ${PGUSER}
        password: ${PGPASSWORD}
        initialize: false
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false #causes logs for DB queries
```

Maybe that helps :)
