### ISSUE TITLE
Gitlab deploys

### ISSUE THREAD

**Issue by amingilani** [flynn/flynn#3560]
Related to #227

Just setup a 5 node cluster, and I'll be moving all my production apps over in the next few days. I must ask though, I love Github but is there a way for me to deploy with Gitlab?

**Comment by josephglanville** [comment]
I think right now the best way to do this is to use your CI system to do the deployments after running your tests. I think Gitlab CI would be capable of this, using either the shell or Docker runners.

If there is a hook system you could look at https://github.com/lmars/flynn-webhook-deploy and see if it can be modified to suit your purposes.

**Comment by MBrouns** [comment]
I've been working on deploying to Flynn from gitlab and used Gitlab CI to great success. My CI step looks like this:
```
deploy to staging:
  environment: staging
  stage: deploy
  image: docker:git
  script:
   - L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L
   - flynn cluster add -p $FLYNN_TLS_PIN $FLYNN_CLUSTER_NAME $FLYNN_CONTROLLER_URL $FLYNN_CONTROLLER_KEY --git-url=$FLYNN_GIT_URL
   - flynn -a otpapi remote add staging
   - git push staging HEAD:master
  when: manual
```

At some point in time I'll make a docker image containing the flynn-cli preinstalled but as it is very fast to install I'm okay with keeping it like this for now
